#  配置 thymeleaf
spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    encoding: utf-8
    mode: HTML
    servlet:
      content-type: text/html
    cache: false

  #   配置数据源
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.1.105:3306/blog?useUnicode=true&characterEncoding=utf8
    username: root
    password: 123456
#    jpa相关设置 sql
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
# 日志 相关设置
logging:
  level:
    root: info
    com.zf: debug
  file:
    name: log/blog.log


